name: Build macOS App

on: [push]

jobs:
  build-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Log Python and Tkinter Versions
      run: |
        echo "Python Version:"
        python --version
        echo "Tkinter Version:"
        python -c "import tkinter; print(tkinter.TkVersion); print(tkinter.TclVersion)"

    - name: Build Application
      run: pyinstaller --onefile --windowed Unlock_Savefiles.py

    - name: Debug PyInstaller Bundling
      run: |
        echo "Contents of dist directory:"
        ls -alh dist/
        echo "Contents of the app bundle:"
        ls -alh dist/Unlock_Savefiles.app/Contents/MacOS

  - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Unlock_Savefiles_Mac
        path: dist/*.app
