name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-10.15  # Using macOS Catalina for broader compatibility
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Application
      run: pyinstaller --onefile --windowed Unlock_Savefiles.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: your-app-macos
        path: dist/your_script
